<?php
/**
 * 1997-2014 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2014 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>

<?php if ($this->getMethodInstance() instanceof Quadra_Be2bill_Model_Several): ?>
    <div class="checkout-review-be2bill checkout-agreements">
        <p><?php echo $this->__('Your payment in %s times:', $this->getMethodInstance()->getNTimes()) ?></p>
        <?php foreach ($this->getMethodInstance()->getAmountByPeriod($this->getFormatedAmount()) as $date => $amount): ?>
            <p class="ul"><?php echo $this->__('%s taken on %s', $this->priceFormat($amount / 100), Mage::helper('core')->formatDate($date, 'short')) ?></p>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
