<?php
/**
 * 1997-2014 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2014 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getRequest()->getParam('method'); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="be2bill-oneclick">
    <div class="page-title">
        <h1><?php echo $this->__('Pay with Be2bill') ?></h1>
    </div>
    <form action="<?php echo $this->getSubmitUrl() ?>" method="post" id="be2bill-oneclick-validate">
        <div class="col2-set">
            <div class="col-1">
                <?php if ($this->getMethodInstance() instanceof Quadra_Be2bill_Model_Several): ?>
                    <h2 class="sub-title"><?php echo $this->__('Pay in %s times your order with a total amount of %s', $this->getMethodInstance()->getNTimes(), $this->priceFormat($this->getQuote()->getBaseGrandTotal())) ?></h2>
                    <p><?php echo $this->__('Your payment in %s times:', $this->getMethodInstance()->getNTimes()) ?></p>
                    <ul class="disc">
                        <?php foreach ($this->getMethodInstance()->getAmountByPeriod($this->getFormatedAmount()) as $date => $amount): ?>
                            <li><?php echo $this->__('%s taken on %s', $this->priceFormat($amount / 100), Mage::helper('core')->formatDate($date, 'short')) ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php if (!$this->getQuote()->getShippingMethod()): ?>
                    <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
                        <h2 class="sub-title"><?php echo $this->__('Select your shipping method') ?></h2>
                        <dl id="shipping-method" class="sp-methods">
                            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                                <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
                                <dd>
                                    <ul>
                                        <?php foreach ($_rates as $_rate): ?>
                                            <li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"'; ?>>
                                                <?php if ($_rate->getErrorMessage()): ?>
                                                    <?php echo $this->escapeHtml($_rate->getErrorMessage()) ?>
                                                <?php else: ?>
                                                    <input name="estimate_method" type="radio" value="<?php echo $this->escapeHtml($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
                                                    <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                                        <?php echo $_excl; ?>
                                                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                                        <?php endif; ?>
                                                    </label>
                                                <?php endif ?>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($this->useCVV()): ?>
                    <div style="padding-top: 25px;">
                        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
                        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

                        <ul class="form-list">
                            <li>
                                <label id="<?php echo $_code ?>_label_cvv_oneclick" for="<?php echo $_code ?>_oneclick" class="required" ><em>*</em><?php echo $this->__('To confirm your payment, please enter the cvv of your card') ?></label>
                                <div class="input-box">
                                    <input id="<?php echo $_code ?>_cc_cid" required="required" class="input-text cvv required-entry validate-cc-cvn" type="text" name="payment[cvv_oneclick]" style="width:3em !important;" autocomplete="off" />
                                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                <?php endif; ?>
                <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
                    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
                </div>
            </div>
            <div id="quote-review" class="col-2">
                <?php echo $this->getChildHtml('be2bill.checkout.oneclick.info.review'); ?>
            </div>
            <div class="buttons-set">
                <?php if ($this->useCVV()): ?>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <?php endif; ?>
                <p class="info"><?php echo Mage::helper('be2bill')->__('Click on "Checkout" will validate automatically your order.') ?></p>
                <button id="order-place" type="submit" title="<?php echo $this->__('Checkout') ?>" class="button"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                <span class="please-wait" id="please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
                </span>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var be2billOneclickValidateForm = new VarienForm('be2bill-oneclick-validate');

        function toggleToolTip(event) {
            if ($('payment-tool-tip')) {
                $('payment-tool-tip').setStyle({
                    top: (Event.pointerY(event) - 160) + 'px',
                    left: (Event.pointerX(event) + 100) + 'px'
                });
                $('payment-tool-tip').toggle();
            }
            Event.stop(event);
        }

        if ($('payment-tool-tip-close')) {
            Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
        }

        if ($('shipping-method')) {
            $$('input.radio').each(function(element) {
                Event.observe(element, 'click', function() {
                    new Ajax.Updater(
                        'quote-review',
                        '<?php echo Mage::getUrl('be2bill/checkout_oneclick/saveShippingMethod') ?>',
                        {
                            parameters: {_secure: true, estimate_method: this.value},
                            onCreate: function() {
                                $('order-place').hide();
                                $('please-wait').show();
                            },
                            onComplete: function() {
                                $('order-place').show();
                                $('please-wait').hide();
                            }
                        }
                    );
                });
            });
        }

        $$('.cvv-what-is-this').each(function(element) {
            Event.observe(element, 'click', toggleToolTip);
        });
        //]]>
    </script>
</div>