<?php
/**
 * 1997-2014 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2014 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php
$versionInfo = Mage::getVersionInfo();
if ($versionInfo['major'] == 1 && $versionInfo['minor'] > 5)
    $canApplyMsrp = $this->canApplyMsrp();
else
    $canApplyMsrp = false;
?>
<?php if ($canApplyMsrp): ?>
    <div class="cart-msrp-totals"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></div>
<?php else: ?>
    <?php foreach($this->getTotals() as $total): ?>
    <tr>
        <th class="a-right" style="border: 0 none;  padding: 0;">
            <?php echo $this->escapeHtml($total->getTitle()); ?>
        </th>
        <td  class="a-right" style="border: 0 none; padding: 0;">
            <?php echo $this->helper('checkout')->formatPrice($total->getValue()) ?>
        </td>
    </tr>
    <?php endforeach; ?>
<?php endif; ?>
