<?php
/**
 * 1997-2014 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2014 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<style type="text/css">
body {
    color: #2F2F2F;
    font: 12px/1.55 Arial,Helvetica,sans-serif;
}

.page-empty {
    background: none repeat scroll 0 0 #FFFFFF;
    padding: 20px;
    text-align: left;
}

.be2bill-template-iframe .be2bill-payment form table { margin: 0; }

.be2bill-payment form table {
    background: none repeat scroll 0 0 #FBFAF6;
    border: 1px solid #BBAFA0;
    margin: 28px 0;
    padding: 10px 25px;
    width: 100%;
}
.be2bill-payment form table tr th { color: #666666; float: left; font-weight: bold; position: relative; z-index: 0; }
.be2bill-payment form table tr td { padding: 0 0 2px; }
.be2bill-payment form table tr td input { background: none repeat scroll 0 0 #FFFFFF; border: 1px solid #B6B6B6; padding: 2px; width: 254px; }
.be2bill-payment form table tr td input:focus { background-color: #EDF7FD; }

#b2b-cvv input { width:3em !important; }
#b2b-buttons td { padding-top: 10px; }
#b2b-errors  {
    border-style:solid !important;
    border-width:1px !important;
    background-position:10px 9px !important;
    background-repeat:no-repeat !important;
    min-height:24px !important;
    padding:8px 8px 8px 32px !important;
    font-size:11px !important;
    font-weight:bold !important;
    overflow:hidden;
    border-color:#f16048;
    background-color:#faebe7;
    background-image:url(<?php echo $this->getSkinUrl('images/i_msg-error.gif') ?>);
    color:#df280a;
}
#b2b-errors ul { list-style:none !important; margin:0 !important; padding:0 !important; }
#b2b-errors ul li { margin:0 0 3px !important; }

#b2b-cvv-comment p { margin: 0; }

#b2b-createalias .divbox { float: left; }
#b2b-createalias .divlabel { float: left; margin-left: 5px; }
#b2b-createalias input { width: 15px; }

#b2b-submit,
#b2b-loading { float: right; }
#b2b-submit {
    background: none repeat scroll 0 0 #F18200;
    border: 1px solid #DE5400;
    color: #FFFFFF;
    display: block;
    font: bold 15px/40px Arial,Helvetica,sans-serif;
    height: 40px;
    background-position: 100% 0;
    text-align: center !important;
    white-space: nowrap;
    width: 75px;
}
#b2b-cancel { display: none !important; }

.invalid { color:#df280a; font-weight:bold; }
</style>
<div class="be2bill-payment">
    %PLACEHOLDER%
</div>