<?php if($this->getCurrencyCount()>1): ?>
<div class="box currency">
    <div class="currency-inner">
        <!--<label for="select-language">Currency: </label>-->
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <?php $active = ($_code==$this->getCurrentCurrencyCode()) ? '_active':''; ?>
            <!--a href="<?php echo $this->helper('directory/url')->getSwitchCurrencyUrl() . 'currency/' . $_code; ?>" title="Set <?php echo $_code ?> as your chosen currency">
                <?php echo $_code; ?>
            </a-->
        <?php endforeach; ?>
        
        <select name="currency" title="<?php echo $this->__('Select Your Currency') ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>

    </div>
</div>
<script type="text/javascript">
//<![CDATA[
function changeCurrency(sObject){
    if(sObject.value){
        setLocation('<?php echo $this->helper('directory/url')->getSwitchCurrencyUrl() ?>currency/'+sObject.value);
    }
}
//]]>
</script>
<?php endif; ?>
