<?php
/**
 * 1997-2014 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2014 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php if ($this->displayPostPayment()): ?>
    <div class="success-collaterals">
        <div class="crosssell">
        <h2><?php echo $this->__('Based on your order, you may be interested in the following items:') ?></h2>
        <?php $_collectionSize = $this->getItemCount() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i = 0; foreach ($this->getItems() as $_item): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
            <ul id="crosssell-products-list" class="crosssell-products-grid">
            <?php endif; ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" /></a>
                    <h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h2>
                    <?php echo $this->getPriceHtml($_item, true) ?>
                    <div class="actions">
                        <?php if ($_item->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Pay') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item, array('method' => 'standard', '_secure' => true)) ?>');"><span><span><?php echo $this->__('Pay') ?></span></span></button>
                        <?php if ($this->canSeveralOneclick($_item)): ?>
                            <button type="button" title="<?php echo $this->__('Pay in 3 times') ?>" class="button btn-cart  last" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item, array('method' => 'several', '_secure' => true)) ?>');"><span><span><?php echo $this->__('Pay in 3 times') ?></span></span></button>
                        <?php endif; ?>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
            <?php endif; ?>
        <?php endforeach; ?>
        <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
        </div>
    </div>
<?php endif; ?>